apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: wcp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcp
  template:
    metadata:
      labels:
        app: wcp
    spec:
      hostNetwork: true
      containers:
      - name: wcp
        image: <IP>:<PORT>/<WCP_IMAGE>:v1.0
        command: ["/opt/dataSourceCreate.sh"]
        ports:
        - containerPort: 7001
